Calculate Total Rate Shot
nepito/calculator-trs pull request #1
Opened 2021-06-13 00:51 UTC by nepito

Haz un función con la que puedas calcular Total Rate Shot (trs).

2021-06-15 05:49 UTC, davidmacer requested changes

2021-06-15 05:49 UTC, davidmacer commented on .github/workflows/actions.yml
> +name: Tests
Solo por ignorancia y pensando en alguna convención, ¿está bien que esta esté en _camel case_? Se me antoja como para que esté en minúscula, pero no sé por qué.

2021-06-15 05:49 UTC, davidmacer commented on .github/workflows/actions.yml
> +    runs-on: ubuntu-18.04
¿No podemos usar ya de una vez la 20.04? ¿Ya estára disponible?

2021-06-15 05:49 UTC, davidmacer commented on Dockerfile
> +FROM r-base:4.0.3
Chingón que ya andemos en la v.4.x.x

2021-06-15 05:49 UTC, davidmacer commented on R/calculate_trs.R
> +calculate_trs <- function(home_shots, away_shots) {
Se me antoja quitarle el `calculate` y ponerle un nombrecito más descriptivo.

2021-06-15 05:49 UTC, davidmacer commented on R/calculate_trs.R
> +calculate_trs <- function(home_shots, away_shots) {
```suggestion
total_rate_shot <- function(home_shots, away_shots) {
```

2021-06-15 05:49 UTC, davidmacer commented on Makefile
> +all: \
No estoy seguro, pero los datos consignados me suena a que nos podrían causar alguna molestia en algún momento si los estamos actualizando a mano. Quizá con una revisión de los `csv` usando algún `datapackage.json`, o por ahí miré que hay un [csv Lint](https://csvlint.io/), pero honestamente no lo he revisado, no sé cómo funciona.

2021-06-15 05:50 UTC, davidmacer commented
@nepito, qué chingón se miran todos esos archivos por los que acabo de pasar. Eres un chingón, loco. Por ahí te dejé algunos comentarios y algunas sugerencias. ;)

2021-06-17 06:21 UTC, nepito commented on Makefile
> +all: \
Tienes razón. El objetivo último y sueño guajiro es que subamos esto al CRAN (de a perdis que lo podamos instalas con `devtools::install_github`). Así que los datos que tenemos aquí ya no los deberíamos de estar cambiando. Pero no veo mal revisar que están correctos. 

Hoy no voy a atender esta sugerencia. Por lo pronto lo pasé al _issue_ #2   Muchas gracias por hacerla :raised_hands:

2021-06-17 06:22 UTC, nepito commented on R/calculate_trs.R
> +calculate_trs <- function(home_shots, away_shots) {
Agregué la sugerencia de `total_rate_shot`. Muchas gracias loco.

2021-06-17 06:23 UTC, nepito commented on Dockerfile
> +FROM r-base:4.0.3
Lo acabo de cambiar a 4.1.0. Ya veremos si sirve si no truena algo

2021-06-17 06:25 UTC, nepito commented on .github/workflows/actions.yml
> +    runs-on: ubuntu-18.04
Simón. Acabo de [revisar](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/#:~:text=October%2029%2C%202020-,GitHub%20Actions%3A%20Ubuntu%2Dlatest%20workflows%20will%20use%20Ubuntu%2D20.04,preview%20mode%20since%20June%202.) y ya está disponible. Parece que también puede servir con `ubuntu-latest`. Por lo pronto dejé el 20.04 y veremos si truena algo o no.

2021-06-17 06:27 UTC, nepito commented on .github/workflows/actions.yml
> +name: Tests
A mí también me gusta más en minúscula. Creo que me suena muy brusco para código de programas. El resto que está el _camel case_ digamos `pull_request`  según yo es parte de los "comandos" del _actions_.

2021-06-17 06:30 UTC, nepito commented
> @nepito, qué chingón se miran todos esos archivos por los que acabo de pasar. Eres un chingón, loco. Por ahí te dejé algunos comentarios y algunas sugerencias. ;)

Muchas gracias la revisión @davidmacer . Contesté a todos tus comentarios y sugerencias. Solo dejé sin atender uno, pero armé un _issue_ para no olvidarlo.

2021-06-19 21:23 UTC, davidmacer approved these changes
Me gusta. Gracias por atender la sugerencia.

2021-07-01 06:30 UTC, davidmacer commented on .github/workflows/actions.yml
> +    runs-on: ubuntu-18.04
¡Excelente!

2021-07-01 06:31 UTC, davidmacer commented on Makefile
> +all: \
Si, tienes razón. Cuando lo subamos al CRAN vamos subir algunos datos para que funcionen las _vignettes_, pero los datos ya no cambiarán. Me parece muy bien que hayas creado un _issue_ diferente para esto, me gusta mucho.

2021-08-12 01:52 UTC, merged